url/shortener/shortener/urls.py
from django.contrib import admin
from django.urls import path, include, reverse


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('url_shortenre.urls')),
]

url/shortener/url_shortenre/urls.py
from django.urls import path
from . import views


app_name = 'url_shortenre'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('short',views.shortened_url, name='short')
]

url/shortener/url_shortenre/models.py
from django.db import models

class url_strings (models.Model):

    url = models.CharField(max_length=1000)
    url_short = models.CharField(max_length = 100)
    url_title = models.CharField(max_length=20, default = 'random')
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.url_title

url/shortener/url_shortenre/views.py
from django.utils import timezone
from django.urls import reverse
from django.views import generic 
from django.http import HttpResponseRedirect

from pyshorteners import Shortener

import validators 

from .models import url_strings 
import os




def shorten(url):
    
    Access_Token = os.environ.get('bitly_token').strip("'")
    url_shortener = Shortener(api_key = Access_Token)
    shortened = url_shortener.bitly.short(url)
    return shortened

class IndexView(generic.ListView):
    template_name = 'url_shortener/index.html'
    model = url_strings
    context_object_name = 'short'

    def get_queryset(self):
        return url_strings.objects.filter(
            pub_date__lte = timezone.now()
        ).order_by('-pub_date')[:5]


def shortened_url(request):

    posted_url = request.POST['post-url']
    if validators.url(posted_url):
        url_original = url_strings(url=posted_url)
        url_original.url_short = shorten(url_original.url)
        url_original.url_title = request.POST['Title']
        url_original.pub_date = timezone.now()
        url_original.save()
    return HttpResponseRedirect(reverse('url_shortenre:index'))

url/shortener/url_shortenre/templates/url_shortener/index.html
<form action= "{% url 'url_shortenre:short' %}"  method="POST">
    {% csrf_token %}
    <br>Enter the url here: <br>
    <input type="text" name="post-url">
    <br>What is it for ? <br>
    <input type="text" name="Title">
    <input type="submit" value="get url">
</form>

{% if short %}
    <ul>
        {% for sh in short %}
        <li>Title: {{ sh.url_title }}  short link: {{ sh.url_short }} </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No URLS are available.</p>
{% endif %}